/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SettingsRouteImport } from './routes/settings'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings': typeof SettingsRoute
  '/splash': typeof SplashRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/splash'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/splash'
  id: '__root__' | '/settings' | '/splash'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRoute: typeof SettingsRoute
  SplashRoute: typeof SplashRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  SettingsRoute: SettingsRoute,
  SplashRoute: SplashRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
